apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: helm-guestbook
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: {{ .Values.memoryDemo.resources.limits.memory | default "200Mi" }}
      requests:
        memory: {{ .Values.memoryDemo.resources.requests.memory | default "100Mi" }}
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "205M", "--vm-hang", "1"]
